### PR TITLE
DEPRECATED: The Ultimate List Guide

### PR DESCRIPTION
**Pull request by MaximumCrash**
### Attention (CC)
@twblack88 
@andytudhope 

## Summary of changes
- Added a box around list link children to ensure 99.9% consistency

## Motivation & Context
- Issue #125 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation Update
- [ ] Other (please describe):

## Does this introduce a breaking change?

_Breaking change is defined as_ **"A fix or feature that would cause existing functionality to change."**

- [ ] Yes
- [x] No

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added/changed necessary documentation (if appropriate)
- [ ] All new and existing tests passed.

## How Has This Been Tested?
Locally

## Screenshots (if appropriate):
Screen Shot 2020-07-09 at 1 26 44 PM
Screen Shot 2020-07-09 at 1 26 48 PM
Screen Shot 2020-07-09 at 1 26 51 PM
Screen Shot 2020-07-09 at 1 26 55 PM
Screen Shot 2020-07-09 at 1 27 03 PM
Screen Shot 2020-07-09 at 1 36 25 PM

### Let's talk about Lists and Formatting

Lists are complex. They may seem overly complex, but there's a reason. The original design spec calls for content that goes in a heading and a sub-body with the added ability to show an arrow link at the end. This is complex because **by design every component must work with every other component** and **no one wants to write MDX like this:**

```
<ListContainer>

//This is one list element. 
<ListElement hasLink hasArrow href="https//website.com">
<ListHeader> Dai </ListHeader>
<ListSubContent> Yadda yadda yadda yadda </ListSubContent>
</ListElement>

</ListContainer>
``` 

The carbon copy of this is:

```
<List>

- [https://website.com](Dai)
   - Yadda yadda yadda yadda

</List>

```

However this simplicity comes with a caveat. Markdown **is picky as hell with spaces and new lines**. 
You may have seen me talk about "**Mind the Gap**" and this is precisely what I mean. 

Let's say we have a list component we write like this:

```
<List>
- <Link to="https://github.com/makerdao/dai-ui"> Dai UI </Link>
    - Components and React-based recipes for various themes

</List> 

```

or this:

```
<List>
- <Link to="https://github.com/makerdao/dai-ui"> Dai UI </Link>
    - Components and React-based recipes for various themes
</List> 
```

Your result will be: 

Screen Shot 2020-07-09 at 3 54 13 PM

Why? 

You didn't put a new line at the top (and bottom) of the list. So Markdown rules treats the text itself, regardless of what you wrote, as individually unique children. ("-", "<Link>...</Link>", "- Components and React-based...")

**The fix: Add a new line at the top (and bottom).** 

If you write something like this:

```
<List>

- <Link to="https://github.com/makerdao/dai-ui"> Dai UI </Link>
    - Components and React-based recipes for various themes
</List> 
```

you will get:

Screen Shot 2020-07-09 at 1 36 25 PM

Why: Because the way MDX converts the MD content into react/html fragments it has an issue with the fragment end. So it will render what you wrote. (Just like it renders code you write) But it will break. 

The Fix: Add a new line at the end. Remember you're not just writing Markdown, you're writing code too.

If you write something like this:

```
<List>

- <Link to="https://github.com/makerdao/dai-ui"> Dai UI </Link>
    - Components and React-based recipes for various themes

</List> 
```

you will get:
Screen Shot 2020-07-09 at 1 26 44 PM

Why: Markdown sometimes recognizes your inner tabs as list elements of the list, sometimes it recognizes it as a direct child, and sometime it recognizes it as an LI. Because this is alll based on spaces and tabs, there's no getting around this. Markdown **is picky**. 

The Fix: See the below examples, for consistency. Build a muscle memory to get better at formatting your MD. 

If you write:

```
<List>

- <Link to="https://github.com/makerdao/dai-ui"> Dai UI </Link>
- Components and React-based recipes for various themes

</List> 

```

you will get:

Screen Shot 2020-07-09 at 1 26 55 PM

Why: The lack of spaces/tabs between the two list elements treat them as individual list element children. They will render as so.

### The Answer

If you write:

```
<List>

- <Link to="https://github.com/makerdao/dai-ui"> Dai UI </Link>
Components and React-based recipes for various themes

</List>
```

or

```
<List>

- <Link to="https://github.com/makerdao/dai-ui"> Dai UI </Link>

    - Components and React-based recipes for various themes

</List> 
```

or 

```
<List>

- [Dai UI](https://github.com/makerdao/dai-ui)
    - Components and React-based recipes for various themes

</List> 
```

you will get:

Screen Shot 2020-07-09 at 1 27 03 PM

Why: This is the very specific case I've written for in the list component by leveraging "-" as a consistent character for recognizing that you want a list element with a header AND subcontent. You would think using a <Link> component like the last code example would work, but gotta remember MDX is picky and they write the rules. 

The Fix: **These are the best practice ways of writing lists**

### CODE REVIEW

**Review by twblack88 — APPROVED** [review]
it's always hilarious when a simple box will do. 😆

**Comment by twblack88** [comment]
I was literally just messing with lists, timely.

**Comment by MaximumCrash** [comment]
@all-contributors please add @MaximumCrash for code

**Comment by MaximumCrash** [comment]
@all-contributers add @MaximumCrash for design and example

**Comment by MaximumCrash** [comment]
@all-contributors add @MaximumCrash for design and example

**Pull request merged**
