### PR TITLE
Tb folders, landing, and readme

### PR DESCRIPTION
**Pull request by twblack88**
### Attention (CC)

@isaacpearl 
@MaximumCrash 
@andytudhope 

## Summary of changes

- Did a bunch of work on the landing page and notes page for governance and risk squad. 
- Added most of the working Mdx filenames for content creators in their /en paths. 
- Edited the README.md file to include `npm install` and then fresh run of yarn. for clarity on newbies

## Motivation & Context

- Issue: #79 and #80

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation Update
- [ ] Other (please describe):

## Does this introduce a breaking change?

_Breaking change is defined as_ **"A fix or feature that would cause existing functionality to change."**

- [x] Yes
- [x] No

no, **and**... I had to delete packagelock.json and i think it's making poolparty mad. 

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added/changed necessary documentation (if appropriate)
- [ ] All new and existing tests passed.

## How Has This Been Tested?

Tested locally 

## Screenshots (if appropriate):

Screen Shot 2020-07-01 at 3 37 46 PM
Screen Shot 2020-07-01 at 3 37 53 PM

## Further comments

This is the beginning of the content mdxs so there are many blank files or just headers to make room for content creators changes. Will open a bug for the video component (second screen shot). Seems like playlists aren't rendered as videos, which is interesting.

### CODE REVIEW

**Review by MaximumCrash — APPROVED** [review]

**Review by MaximumCrash — CHANGES_REQUESTED** [review]
@twblack88 Your build is failing due to one of your files being empty. Here's the error I see

```error You have an empty file in the "src/pages" directory at "content/en/funding/development-grants/grantee-playbook.mdx". Please remove it or make it a valid component```

So if you look for the grantee-playbook.mdx and it's empty I'd either remove it or add some temporary copy you'd like to render.

**Comment by twblack88** [comment]
Gotcha, yeah i think i staged the changes after creation but not saving the small amount of copy in the files. giving it another go.

**Comment by MaximumCrash** [comment]
@twblack88 in your index file for ```governance_and_risk_meetings``` you should write internal urls like so:

```"/learn/governance/frequent-discussion-topics"``` 

instead of 

```"../Learn/Governance/frequent-discussion-topics.mdx"```

Notice that you don't need the file ending and you don't need the dot notation. 
You should write a url instead of a relative path because relative paths don't work in urls.

Also notice that the url is not uppercase "Learn" but "learn". The url must match the file name.

Here's a resource on links from gatsby [Gatsby Link API](https://www.gatsbyjs.org/docs/gatsby-link/#replace-a-tags-with-the-link-tag-for-local-links)

**Review by MaximumCrash — APPROVED** [review]

**Comment by MaximumCrash** [comment]
@andytudhope I've added a new component to this PR. Here's the spec for documentation:

### The Video Component

Sometimes we need youtube playlists for our embeds. Unfortunately the gatsby-remark-video-embed plugin does not support playlists. Fortunately we can build our own work around. Introducing, the video component:

```md
<Video src="https://www.youtube.com/embed/videoseries?list=PLLzkWCj8ywWNq5-90-Id6VPSsrk4OWVan"/>
```

The props for this component are: 
- ```src``` which takes in a url **(specifically an iframe embed url)** and outputs a responsive iframe with your content. 
- ```title``` a title to provide for the iframe for accessibility. If no title is provided the a11y title will be "Inline Iframe Video"

**NOTE: Embedding a youtube video is much different than a playlist and requires a specific url with ```videoseries?list=``` instead of ```playlist?=```. See [here](https://support.google.com/youtube/answer/171780?hl=en) about it.**

### Why not just support iframes? 

MDX will only allow components we specify in the shortcodes **OR** MD elements. We can't use raw html in MDX unless we follow the MD spec. (And I doubt anyone wants to make an iframe responsive) This serves as a helper for getting around youtube playlists, but I still recommend using the inline video spec (ie. ```video: https://urltoyoutubevideo.com```) for regular inline videos.

**Pull request merged**
